### ISSUE TITLE
[epic] User Profiles

### ISSUE THREAD

**Issue by shorn-gnosis** [CirclesUBI/circles-sdk#1]
### Overview:

- The Circles “user profiles” feature will enable any user to create a unique username (alias) and avatar (image data) for their profile.
- The SDK will enable a users profile data to be stored, edited and retrieved.
- Avatar image data will be stored on IPFS.
- Usernames should be searchable.
- Developers building on the Circles SDK will set the endpoint in their application to point to either their own self-hosted Circles node, or a publicly available Circles node endpoint.

Note: _User profile info will be public(ly searchable) information. Therefore we need to ensure people are aware of the implications of using real names or real pictures._

### To do:
- [ ]

**Comment by benjaminbollen** [comment]
I would add that for now these should only be considered public(ly searchable) information. So people should not be encouraged to use their real names or real pictures (they can of course if they wish so)

**Comment by shrn-werk** [comment]
closing this issue given we've now moved away from using ceramic / composedb
